'use client'
import { useState, FormEvent } from 'react'
import { signIn } from 'next-auth/react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'

export default function SignUpForm({
  oauthProviders = [],
}: {
  oauthProviders?: ('github' | 'google')[]
}) {
  const router = useRouter()
  const [email,        setEmail]        = useState('')
  const [password,     setPassword]     = useState('')
  const [error,        setError]        = useState('')
  const [loading,      setLoading]      = useState(false)
  const [demoLoading,  setDemoLoading]  = useState(false)
  const [oauthLoading, setOauthLoading] = useState<string | null>(null)

  const submit = async (e: FormEvent) => {
    e.preventDefault()
    setError('')
    setLoading(true)
    try {
      const res = await fetch('/api/auth/signup', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password }),
      })
      if (!res.ok) {
        const data = await res.json() as { error?: string }
        setError(data.error ?? 'Sign up failed')
        return
      }
      const result = await signIn('credentials', { email, password, redirect: false })
      if (result?.error) { setError('Account created — please sign in'); return }
      router.push('/account')
      router.refresh()
    } catch {
      setError('Sign up failed — try again')
    } finally {
      setLoading(false)
    }
  }

  const oauthSignIn = async (provider: 'github' | 'google') => {
    setOauthLoading(provider)
    try {
      await signIn(provider, { callbackUrl: '/' })
    } catch {
      setOauthLoading(null)
    }
  }

  const tryDemo = async () => {
    setDemoLoading(true)
    setError('')
    try {
      const res = await fetch('/api/auth/demo', { method: 'POST' })
      if (!res.ok) { setError('Demo unavailable — try again'); setDemoLoading(false); return }
      const { token: demoToken } = await res.json() as { token: string }
      const result = await signIn('credentials', { demoToken, redirect: false })
      if (result?.error) { setError('Demo sign-in failed'); setDemoLoading(false); return }
      router.push('/')
      router.refresh()
    } catch {
      setError('Demo unavailable — try again')
      setDemoLoading(false)
    }
  }

  const anyLoading = loading || demoLoading || !!oauthLoading

  return (
    <div className="min-h-screen bg-surface-base flex items-center justify-center px-4">
      <div className="w-full max-w-sm">
        <div className="mb-8">
          <h1 className="text-xl font-semibold text-text-primary">Create account</h1>
          <p className="text-sm font-medium text-text-secondary mt-1">ResumeLoop</p>
          <p className="text-xs text-text-muted mt-1.5 leading-relaxed">
            Paste a job description — get a tailored 1-page resume, fit score, and outreach drafts, generated by AI.
          </p>
        </div>

        {/* Try Demo */}
        <button
          onClick={tryDemo}
          disabled={anyLoading}
          className="w-full flex items-center justify-center gap-2 py-2 px-4 bg-indigo-950 hover:bg-indigo-900 disabled:opacity-40 rounded text-sm font-medium text-indigo-300 transition-colors border border-indigo-700 mb-4"
        >
          {demoLoading ? 'Loading demo…' : '✦ Try Demo — no account needed'}
        </button>

        {/* OAuth providers */}
        {oauthProviders.length > 0 && (
          <div className="space-y-2 mb-4">
            {oauthProviders.includes('github') && (
              <button
                onClick={() => oauthSignIn('github')}
                disabled={anyLoading}
                className="w-full flex items-center justify-center gap-2 py-2 px-4 bg-surface-raised hover:bg-surface-overlay disabled:opacity-40 rounded text-sm font-medium text-text-secondary transition-colors border border-border-default"
              >
                <svg viewBox="0 0 24 24" className="w-4 h-4 fill-current"><path d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0 1 12 6.844a9.59 9.59 0 0 1 2.504.337c1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.02 10.02 0 0 0 22 12.017C22 6.484 17.522 2 12 2z" /></svg>
                {oauthLoading === 'github' ? 'Redirecting…' : 'Continue with GitHub'}
              </button>
            )}
            {oauthProviders.includes('google') && (
              <button
                onClick={() => oauthSignIn('google')}
                disabled={anyLoading}
                className="w-full flex items-center justify-center gap-2 py-2 px-4 bg-surface-raised hover:bg-surface-overlay disabled:opacity-40 rounded text-sm font-medium text-text-secondary transition-colors border border-border-default"
              >
                <svg viewBox="0 0 24 24" className="w-4 h-4"><path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"/><path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/><path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05"/><path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/></svg>
                {oauthLoading === 'google' ? 'Redirecting…' : 'Continue with Google'}
              </button>
            )}
          </div>
        )}

        <div className="flex items-center gap-3 mb-6">
          <div className="flex-1 h-px bg-border-subtle" />
          <span className="text-xs text-text-secondary">or create account</span>
          <div className="flex-1 h-px bg-border-subtle" />
        </div>

        <form onSubmit={submit} className="space-y-4">
          <div>
            <label htmlFor="email" className="text-xs text-text-muted block mb-1">Email</label>
            <input
              id="email" type="email" autoComplete="email" required
              value={email} onChange={e => setEmail(e.target.value)}
              className="w-full text-sm bg-surface-card border border-border-default rounded px-3 py-2 text-text-secondary focus:outline-none focus:border-indigo-500"
              placeholder="you@example.com"
            />
          </div>

          <div>
            <label htmlFor="password" className="text-xs text-text-muted block mb-1">
              Password <span className="text-text-secondary">(min 8 characters)</span>
            </label>
            <input
              id="password" type="password" autoComplete="new-password" required minLength={8}
              value={password} onChange={e => setPassword(e.target.value)}
              className="w-full text-sm bg-surface-card border border-border-default rounded px-3 py-2 text-text-secondary focus:outline-none focus:border-indigo-500"
              placeholder="••••••••"
            />
          </div>

          {error && <p className="text-xs text-red-400">{error}</p>}

          <button
            type="submit" disabled={anyLoading}
            className="w-full py-2 px-4 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-40 rounded text-sm font-medium transition-colors"
          >
            {loading ? 'Creating account…' : 'Create account'}
          </button>
        </form>

        <p className="text-xs text-text-muted mt-6 text-center">
          Already have an account?{' '}
          <Link href="/auth/signin" className="text-indigo-400 hover:text-indigo-300">Sign in</Link>
        </p>
      </div>
    </div>
  )
}
